/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard.$guildId'
import { Route as McpConsentRouteImport } from './routes/mcp_.consent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/dashboard/$guildId',
  path: '/dashboard/$guildId',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConsentRoute = McpConsentRouteImport.update({
  id: '/mcp_/consent',
  path: '/mcp/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/mcp/consent': typeof McpConsentRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/mcp/consent': typeof McpConsentRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/dashboard/$guildId': typeof DashboardGuildIdRoute
  '/mcp_/consent': typeof McpConsentRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/privacy'
    | '/sign-in'
    | '/.well-known/$'
    | '/api/$'
    | '/dashboard/$guildId'
    | '/mcp/consent'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/privacy'
    | '/sign-in'
    | '/.well-known/$'
    | '/api/$'
    | '/dashboard/$guildId'
    | '/mcp/consent'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/privacy'
    | '/sign-in'
    | '/.well-known/$'
    | '/api/$'
    | '/dashboard/$guildId'
    | '/mcp_/consent'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DashboardGuildIdRoute: typeof DashboardGuildIdRoute
  McpConsentRoute: typeof McpConsentRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/dashboard/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp_/consent': {
      id: '/mcp_/consent'
      path: '/mcp/consent'
      fullPath: '/mcp/consent'
      preLoaderRoute: typeof McpConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  DashboardGuildIdRoute: DashboardGuildIdRoute,
  McpConsentRoute: McpConsentRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
